version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tarkov-stats"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sgmyzjq63ok3"
s3_prefix = "tarkov-stats"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

