AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: SAM application for collecting EFT Raid statistics from screenshots of the Raid End screen.

Resources:
    SourceImageBucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-source-images"
            
    InvokeTextract:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: InvokeTextract/src/app.lambda_handler
            Runtime: python3.6
            CodeUri: .
            Description: Invokes Textract service for S3 Objects.
            MemorySize: 256
            Timeout: 30
            Policies:
                - Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action: s3:GetObject
                      # Building the resource name the same as the BucketName above to avoid circular dependancies
                      # See: https://github.com/awslabs/serverless-application-model/issues/138
                      Resource: !Sub "arn:aws:s3:::${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-source-images*"
                    - Effect: Allow
                      Action: textract:StartDocumentTextDetection
                      Resource: '*'
            Events:
                CreateScreenshotEvent:
                    Type: S3
                    Properties:
                        Bucket: !Ref SourceImageBucket
                        Events: s3:ObjectCreated:*