AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  addTarkovRaid:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: addTarkovRaid
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::832044451952:role/service-role/addTarkovRaid-role-aqpnl5na'
      Runtime: nodejs12.x
      Timeout: 3
